[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/notion-proxy"
  status = 200
  force = true

 [build.environment]
  NODE_VERSION = "18.17.1" 
